package br.com.windel.pos.enums

enum class TransactionsEnum(val value: String){
    CREDITO_GENERICO("CREDITO_GENERICO"),
    CREDITO("CREDITO"),
    PARCELADO_LOJISTA("PARCELADO_LOJISTA"),
    PARCELADO_EMISSOR("PARCELADO_EMISSOR"),
    REPAY("REPAY"),
    DEBITO("DEBITO"),
    DEBITO_VISTA("DEBITO_VISTA"),
    BANRICOMPRAS("BANRICOMPRAS"),
    PREDATADO("PREDATADO"),
    DEBITO_PARCELADO("DEBITO_PARCELADO”"),
    CREDITO1M("CREDITO1M"),
    VOUCHER("VOUCHER"),
    WALLET("WALLET"),
    PIX("PIX"),
    DIGITADA("DIGITADA"),
    VEROPAY("VEROPAY")
}